---
# tasks file for mail
- name: Postfix 파일 설정 - /etc/postfix/main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  changed_when: true
  notify: Restart postfix

- name: Dovecot 파일 설정 - /etc/dovecot/dovecot.conf
  ansible.builtin.template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'
  changed_when: true
  notify: Restart dovecot

- name: Dovecot 파일 설정 - /etc/dovecot/conf.d/10-auth.conf
  ansible.builtin.template:
    src: 10-auth.conf.j2
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
    mode: '0644'

- name: Dovecot 파일 설정 - /etc/dovecot/conf.d/10-mail.conf
  ansible.builtin.template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode: '0644'

- name: Dovecot 파일 설정 - /etc/dovecot/conf.d/10-master.conf
  ansible.builtin.template:
    src: 10-master.conf.j2
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode: '0644'

- name: Dovecot 파일 설정 - /etc/dovecot/conf.d/10-ssl.conf
  ansible.builtin.template:
    src: 10-ssl.conf.j2
    dest: /etc/dovecot/conf.d/10-ssl.conf
    owner: root
    group: root
    mode: '0644'
