---
# vars file for web
apachepath: /usr/local/apache-tomcat-10.1.43
tomcatpath: /usr/local/tomcat
apachedownload: https://downloads.apache.org/tomcat/tomcat-10/v10.1.43/bin/apache-tomcat-10.1.43.tar.gz
dns: hyun
